blank_issues_enabled: false
contact_links:
  - name: OE-O Discord
    url: http://oe-o.tk/discord
    about: We can support you with any modding matters on our discord.
  - name: OE-O Site
    url: http://oe-o.tk
    about: Feel free to checkout our site!
