blank_issues_enabled: true
contact_links:
  - name: OE-O Discord
    url: http://oe-o.tk/discord
    about: We can support you with any modding matters on our discord.
  - name: OE-O Site
    url: http://oe-o.tk
    about: Feel free to checkout our site!
  - name: Bug Reports
    about: If you are reporting a bug, just create a blank issue with the bug label and we will see the bug shortly.
